In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import yfinance as yf
from pandas_datareader import data as pdr
import warnings

yf.pdr_override() 
plt.style.use("fivethirtyeight")
warnings.filterwarnings("ignore")

yesterday = datetime.now() - timedelta(1)
yesterday = datetime.strftime(yesterday, '%Y-%m-%d')
today = datetime.strftime(datetime.now(), '%Y-%m-%d')

In [2]:
## FUNCTIONS
def getMonthlyData(ticker="SPY", start="1994-01-01", end="2022-10-01"):
    data = yf.download(ticker, start, end)
    return data.resample('M').ohlc()['Close'].reset_index()
    
def funcMomentum(data):
    data['shift1'] = data['close'].shift(1)
    data['shift3'] = data['close'].shift(3)
    data['shift6'] = data['close'].shift(6)
    data[['Date', 'close','shift1','shift3','shift6']]
    data = data.dropna(axis=0)
    data["momentum"] = (12*(data['close']/data['shift1']-1)) + (4*(data['close']/data['shift3']-1)) + (2*(data['close']/data['shift6']-1))
    return data

In [3]:
def acceleratingDualMomentum(stocks=["spy","scz","tip"]):
    ## Getting Data
    namespace = globals()
    for i in stocks:
        namespace['%s_data' % str(i)] = getMonthlyData(i, end=yesterday)

    ## Creating shift columns and calculating momentum
    for i in stocks:
        namespace['%s_data' % str(i)] = funcMomentum(namespace['%s_data' % str(i)])
        
   
    ## series lenght ## hardcoded because ETF release date won't change.
    date = scz_data['Date'] 
    spy_data2 = spy_data.copy()
    spy_data2 = spy_data2.tail(len(date))
    tip_data2 = tip_data.copy()
    tip_data2 = tip_data.tail(len(date))


    ## ETF Picking
    etf = []
    ret = []
    for i in range(0, len(date)):
        if ((spy_data2['momentum'].iloc[i] > scz_data['momentum'].iloc[i]) & (spy_data2['momentum'].iloc[i] > 0)):
            etf.append('SPY')
            ret.append(spy_data2['momentum'].iloc[i])
        elif ((scz_data['momentum'].iloc[i] > spy_data2['momentum'].iloc[i]) & (scz_data['momentum'].iloc[i] > 0)):
            etf.append('SCZ')
            ret.append(scz_data['momentum'].iloc[i])
        else:
            etf.append('TIP')
            ret.append(tip_data2['momentum'].iloc[i])
            
    ## Returns        
    ret_data = {'date':date, 'etf':etf, 'ret':ret, 'Cumulative Returns':np.cumsum(ret)}
    returns = pd.DataFrame(data=ret_data)
    return returns

In [4]:
adm = acceleratingDualMomentum()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
adm

                         date  etf       ret  Cumulative Returns
6   2008-06-30 00:00:00-04:00  TIP  0.084386            0.084386
7   2008-07-31 00:00:00-04:00  TIP -0.234209           -0.149823
8   2008-08-31 00:00:00-04:00  TIP -0.104282           -0.254105
9   2008-09-30 00:00:00-04:00  TIP -0.970327           -1.224432
10  2008-10-31 00:00:00-04:00  TIP -1.862806           -3.087237
..                        ...  ...       ...                 ...
174 2022-06-30 00:00:00-04:00  TIP -1.086467          109.632408
175 2022-07-31 00:00:00-04:00  SPY  0.936385          110.568793
176 2022-08-31 00:00:00-04:00  TIP -0.816309          109.752484
177 2022-09-30 00:00:00-04:00  TIP -1.581367          108.171117
178 2022-10-31 00:00:00-04:00  TIP -0.617608          107.553509

[173 rows x 4 columns]

In [5]:
stocks=["spy","scz","tip"]
## Getting Data
namespace = globals()
for i in stocks:
    namespace['%s_data' % str(i)] = getMonthlyData(i, end=yesterday)

## Creating shift columns and calculating momentum
for i in stocks:
    namespace['%s_data' % str(i)] = funcMomentum(namespace['%s_data' % str(i)])

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [6]:
## series lenght ## hardcoded because ETF release date won't change.
date = scz_data['Date'] 
spy_data2 = spy_data.copy()
spy_data2 = spy_data2.tail(len(date))
tip_data2 = tip_data.copy()
tip_data2 = tip_data.tail(len(date))


## ETF Picking
etf = []
ret = []
for i in range(0, len(date)):
    if ((spy_data2['momentum'].iloc[i] > scz_data['momentum'].iloc[i]) & (spy_data2['momentum'].iloc[i] > 0)):
        etf.append('SPY')
        ret.append(spy_data2['momentum'].iloc[i])
    elif ((scz_data['momentum'].iloc[i] > spy_data2['momentum'].iloc[i]) & (scz_data['momentum'].iloc[i] > 0)):
        etf.append('SCZ')
        ret.append(scz_data['momentum'].iloc[i])
    else:
        etf.append('TIP')
        ret.append(tip_data2['momentum'].iloc[i])

In [7]:
## Returns        
ret_data = {'date':date, 'etf':etf, 'ret':ret, 'Cumulative Returns':np.cumsum(ret)}
returns = pd.DataFrame(data=ret_data)
returns

                         date  etf       ret  Cumulative Returns
6   2008-06-30 00:00:00-04:00  TIP  0.084386            0.084386
7   2008-07-31 00:00:00-04:00  TIP -0.234209           -0.149823
8   2008-08-31 00:00:00-04:00  TIP -0.104282           -0.254105
9   2008-09-30 00:00:00-04:00  TIP -0.970327           -1.224432
10  2008-10-31 00:00:00-04:00  TIP -1.862806           -3.087237
..                        ...  ...       ...                 ...
174 2022-06-30 00:00:00-04:00  TIP -1.086467          109.632408
175 2022-07-31 00:00:00-04:00  SPY  0.936385          110.568793
176 2022-08-31 00:00:00-04:00  TIP -0.816309          109.752484
177 2022-09-30 00:00:00-04:00  TIP -1.581367          108.171117
178 2022-10-31 00:00:00-04:00  TIP -0.617608          107.553509

[173 rows x 4 columns]